# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bilibili每日任务

on:
  workflow_dispatch:
  schedule:
    - cron: '10 */1 * * *' #每小时的10分运行
  watch:
    types: started
  repository_dispatch:
    types: lightning
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: Cache config & cookie
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-config-cookie
        with:
          path: |
            .config
            .cookies
          key: ${{ runner.os }}-${{ env.cache-name }}
      - name: npm install
        run: |
          npm install
      - name: '运行 【Bilibili每日任务】'
        run: |
          npm run start
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BILI_USERNAME: ${{ secrets.BILI_USERNAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          ROOM_ID: ${{ secrets.ROOM_ID }}
          DEBUG: ${{ secrets.DEBUG }}
